export type CardsTableType = {
    cardArt: string;
    cardArtPrompt: string;
    cardAttack: string;
    cardEnergyAlignment: string | null;
    cardCreator: string;
    cardDefense: string;
    cardEnergyValue: number;
    cardEnergyCost?: { [key: string]: number };
    cardLoreText: string;
    cardGrade: string;
    cardName: string;
    cardPrompt: string;
    cardRender: string;
    cardSpeed: string;
    cardSubType: string[];
    cardSuperType: string;
    cardText: string;
    cardType: string;
    cardUnitType?: string;
    id: number;
    user_id: string;
    created_at: string;
    updated_at?: string;
    cardAnomalyMode?: string | null;
    cardAnomalyModeName?: string;
    cardAnomalyModeText?: string;
    cardAnomalyModeLoreText?: string;
    cardAnomalyModeGrade?: string | null;
    art_prompt_options: string[] | null;
};
