export type CardsTableType = {
    cardAnomalyModeFlavorText?: string;
    cardAnomalyModeName?: string;
    cardAnomalyModeText?: string;
    cardArt: string;
    cardArtPrompt: string;
    cardAttack: string;
    cardEnergyAlignment: string;
    cardCreator: string;
    cardDefense: string;
    cardEnergyValue: number;
    cardEnergyCost?: { [key: string]: number };
    cardLoreText: string;
    cardGrade: string;
    cardName: string;
    cardPrompt: string;
    cardRender: string;
    cardSpeed: string;
    cardSubType: string[];
    cardSuperType: string;
    cardText: string;
    cardType: string;
    cardUnitType?: string;
    id: number;
    user_id: string;
    created_at: string;
    updated_at?: string;
};
